# Generated by Django 2.0 on 2020-04-02 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testcase_manage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='res_code',
        ),
        migrations.AlterField(
            model_name='testcase',
            name='method',
            field=models.CharField(choices=[('POST', 'POST'), ('GET', 'GET')], default='POST', max_length=32, verbose_name='请求方式'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='modular_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_manage.Modular', verbose_name='所属项目 -> 模块'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='url',
            field=models.URLField(help_text='e.g. /api/v1/face/boarding/push-plan', verbose_name='接口路径'),
        ),
    ]
