# Generated by Django 2.0 on 2020-04-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase_manage', '0002_auto_20200402_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='desc',
            field=models.TextField(blank=True, verbose_name='用例简要描述'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='url',
            field=models.CharField(help_text='e.g. /api/v1/face/boarding/push-plan', max_length=100, verbose_name='接口路径'),
        ),
    ]
