# Generated by Django 2.0 on 2020-04-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase_manage', '0003_auto_20200402_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='case_file',
            field=models.FileField(blank=True, help_text='对于流程测试,需上传流程测试脚本', upload_to='testCase', verbose_name='用例测试脚本'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='case_type',
            field=models.CharField(choices=[('单接口', '单接口'), ('单接口', '流程')], default='单接口', max_length=64, verbose_name='用例类型'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='body',
            field=models.TextField(blank=True, default='---\ndata: {}\n    ', help_text='以yaml格式输入请求信息', verbose_name='请求体列表'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='casename',
            field=models.CharField(help_text='必填', max_length=50, verbose_name='用例名'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='desc',
            field=models.TextField(blank=True, help_text='选填', verbose_name='用例简要描述'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='url',
            field=models.CharField(help_text='必填: e.g. /api/v1/face/boarding/push-plan', max_length=100, verbose_name='接口路径'),
        ),
    ]
