# Generated by Django 2.0 on 2020-04-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase_manage', '0005_auto_20200402_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='case_file',
        ),
        migrations.AddField(
            model_name='testcase',
            name='file_path',
            field=models.CharField(blank=True, help_text='e.g xx/xx/xx', max_length=128, verbose_name='启动脚本路径'),
        ),
    ]
