# Generated by Django 2.0 on 2020-04-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase_manage', '0007_auto_20200407_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='certificate',
            field=models.TextField(blank=True, help_text='证书字符,选填', verbose_name='证书'),
        ),
    ]
