# Generated by Django 2.0 on 2020-04-01 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modular',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='模块名')),
                ('host', models.CharField(help_text='e.g. http://127.0.0.1:8000', max_length=50, verbose_name='HOST')),
            ],
            options={
                'verbose_name': '模块管理',
                'verbose_name_plural': '模块管理',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='项目名称')),
                ('type', models.CharField(choices=[('Web', 'Web'), ('App', 'App'), ('其他', '其他')], max_length=50, verbose_name='项目类型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '项目管理',
                'verbose_name_plural': '项目管理',
            },
        ),
        migrations.AddField(
            model_name='modular',
            name='to_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modular', to='product_manage.Product', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='modular',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
    ]
