# Generated by Django 2.0 on 2020-04-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manage', '0002_auto_20200401_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='notifier',
        ),
        migrations.AddField(
            model_name='product',
            name='notifier',
            field=models.ManyToManyField(null=True, related_name='product', to='product_manage.Notifier', verbose_name='邮件抄送人'),
        ),
    ]
