# Generated by Django 2.0 on 2020-04-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manage', '0003_auto_20200401_2150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifier',
            options={'ordering': ['-update_time'], 'verbose_name': '邮件抄送人', 'verbose_name_plural': '邮件抄送人'},
        ),
        migrations.AlterField(
            model_name='notifier',
            name='desc',
            field=models.TextField(blank=True, help_text='选填', verbose_name='描述'),
        ),
    ]
